### ISSUE TITLE
README.md instructions result in error

### ISSUE THREAD

**Issue by codyburleson** [CarbonLDP/angular2-jspm-carbonldp-boilerplate#1]
I followed the instructions for the angular2-jspm-carbon-boilerplate as written and get an error when attempting to run it using gulp serve. See attached image.

![errorrunningboilerplate](https://cloud.githubusercontent.com/assets/7317733/18810494/8a96c15a-825d-11e6-8614-57e07ce052c0.jpg)

Note: I tried changing jspm.config.js version of plugin-typescript to 5.1.1 and this removed the initial error after running jspm install again.

`"plugin-typescript"                : "github:frankwallis/plugin-typescript@5.1.1",`

I then get a view rendered with "home [Login]' and nothing else in the view.

There is then the following error in the browser console:

`Failed to parse SourceMap: http://localhost:8045/src/assets/node_modules/Promise.js.map
`
If I click the Login button, I just get an error in the console like this:

`EXCEPTION: Error: Uncaught (in promise): UnauthorizedError:`

I also notice that I guess we need to update the boiler plate to Angular 2 final.

**Comment by MiguelAraCo** [comment]
The boilerplate was updated to use Angular2 latest version. This issue is no longer present.
